# Tentative schedule {.unnumbered}

## 11 week Schedule

|        | Topic                          | Textbook              | Agenda       |
|------------------|------------------|------------------|------------------|
| Day 1  | Syllabus Day                   |                       | Syllabus Day |
| Day 2  | Intro to R                     | Preface and Chapter 1 | Activity 01  |
| Day 3  | Data Visualization             | Sections 2.0-2.3      | Activity 02  |
| Day 4  | Data Visualization             | Sections 2.4-2.6      | Activity 03  |
| Day 5  | Data Visualization             | Sections 2.7-2.9      | Activity 04  |
| Day 6  | Data Wrangling                 | Sections 3.0-3.3      | Activity 05  |
| Day 7  | Data Wrangling                 | Sections 3.4-3.9      | Activity 06  |
| Day 8  | Tidy Data                      | Chapter 4             | Activity 07  |
| Day 9  | Exam 1                         |                       |              |
| Day 10 | Regression                     | Sections 5.0-5.1      | Activity 08  |
| Day 11 | Regression                     | Sections 5.2-5.4      | Activity 09  |
| Day 12 | Regression                     | Sections 6.0-6.1      | Activity 10  |
| Day 13 | Regression                     | Sections 6.2-6.4      | Activity 11  |
| Day 14 | Randomization + Causality      | Chapter 7             | Activity 12  |
| Day 15 | Populations + Generalizability | Chapter 8             | Activity 13  |
| Day 16 | Exam 2                         |                       |              |
| Day 17 | Distributions                  | Sections 9.0-9.1      | Activity 14  |
| Day 18 | Repeated Sampling              | Sections 9.2-9.4      | Activity 15  |
| Day 19 | CLT                            | Sections 9.5-9.7      | Activity 16  |
| Day 20 | Confidence Intervals           | Chapter 10            | Activity 17  |
| Day 21 | Confidence Intervals           | Chapter 10            | Activity 17  |
| Day 22 | P-values                       | Chapter 11            | Activity 18  |
| Day 23 | Hypothesis Testing             | Chapter 12            | Activity 19  |
| Day 24 | Hypothesis Testing             | Chapter 12            | Activity 20  |
| Day 25 | Hypothesis Testing             | Chapter 12            | Activity 20  |
| Day 26 | Review                         | Chapter 13            |              |
| Day 27 | Exam 3                         |                       |              |

## 15 week Schedule

|        | Topic                          | Textbook              | Agenda       |
|------------------|------------------|------------------|------------------|
| Day 1  | Syllabus Day                   |                       | Syllabus Day |
| Day 2  | Intro to R                     | Preface and Chapter 1 | Activity 01  |
| Day 3  | Data Visualization             | Sections 2.0-2.3      | Activity 02  |
| Day 4  | Data Visualization             | Sections 2.4-2.6      | Activity 03  |
| Day 5  | Data Visualization             | Sections 2.7-2.9      | Activity 04  |
| Day 6  | Data Wrangling                 | Sections 3.0-3.3      | Activity 05  |
| Day 7  | Data Wrangling                 | Sections 3.4-3.9      | Activity 06  |
| Day 8  | Tidy Data                      | Chapter 4             | Activity 07  |
| Day 9  | Putting it together            |                       |              |
| Day 10 | Review                         |                       |              |
| Day 11 | Exam 1                         |                       |              |
| Day 12 | Regression                     | Sections 5.0-5.1      | Activity 08  |
| Day 13 | Regression                     | Sections 5.2-5.4      | Activity 09  |
| Day 14 | Regression                     | Sections 6.0-6.1      | Activity 10  |
| Day 15 | Regression                     | Sections 6.2-6.4      | Activity 11  |
| Day 16 | Randomization + Causality      | Chapter 7             | Activity 12  |
| Day 17 | Populations + Generalizability | Chapter 8             | Activity 13  |
| Day 18 | Distributions                  | Sections 9.0-9.1      | Activity 14  |
| Day 19 | Repeated Sampling              | Sections 9.2-9.4      | Activity 15  |
| Day 20 | CLT                            | Sections 9.5-9.7      | Activity 16  |
| Day 21 | Review                         |                       |              |
| Day 22 | Exam 2                         |                       |              |
| Day 23 | Confidence Intervals           | Chapter 10            | Activity 17  |
| Day 24 | Confidence Intervals           | Chapter 10            | Activity 17  |
| Day 25 | P-values                       | Chapter 11            | Activity 18  |
| Day 26 | Hypothesis Testing             | Chapter 12            | Activity 19  |
| Day 27 | Hypothesis Testing             | Chapter 12            | Activity 20  |
| Day 28 | Hypothesis Testing             | Chapter 12            | Activity 20  |
| Day 29 | Hypothesis Testing             | Chapter 12            | Activity 21  |
| Day 30 | Putting it all together        | Chapter 13            | Activity 22  |
| Day 31 | Putting it all together        | Chapter 13            | Activity 22  |
| Day 32 | CI - SD                        |                       |              |
| Day 33 | CI - SD                        |                       |              |
| Day 34 | Hypothesis - SD                |                       |              |
| Day 35 | Hypothesis - SD                |                       |              |
| Day 36 |                                |                       |              |
| Day 37 |                                |                       |              |
| Day 38 | Review                         |                       |              |
| Day 39 | Exam 3                         |                       |              |
| Day 40 | Project Work Day               |                       |              |
| Day 41 | Project Work Day               |                       |              |
| Day 42 | Project Work Day               |                       |              |
| Day 43 | Project Work Day               |                       |              |
