project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Statistics and Data Science: Instructor's Guide"
  author: "Danielle Sass"
  date: "9/08/2022"
  chapters:
    - index.qmd
    - 00-syllabi.qmd
    - 00-schedule.qmd
    - 01-content.qmd
    - 02-content.qmd
    - 03-content.qmd
    - 04-content.qmd
    - 05-content.qmd
    - 06-content.qmd
    - 07-content.qmd
    - 08-content.qmd
    - references.qmd
  

bibliography: references.bib

format:
  html:
    theme: [cosmo, style.scss]
    number-depth: 1
    toc-depth: 2
    echo: fenced
    warning: false
    message: false
    self-contained: true
    self-contained-math: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: columns.tex
    number-depth: 1
    toc-depth: 2
    echo: fenced
    warning: false
    message: false
    self-contained: true
    self-contained-math: true

editor: visual

