project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Spatial Analysis with R"
  author: "Danielle Sass"
  date: "8/31/2022"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

