project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Statistics and Data Science: Instructor's Guide"
  author: "Danielle Sass"
  downloads: [pdf]
  date: today
  date-format: iso
  site-url: https://dsass1.github.io/stat202_instructors_guide/
  repo-url: https://github.com/dsass1/stat202_instructors_guide
  chapters:
    - index.qmd
    - 00-syllabi.qmd
    - 00-schedule.qmd
    - 01-content.qmd
    # - 02-content.qmd
    # - 03-content.qmd
    # - 04-content.qmd
    # - 05-content.qmd
    # - 06-content.qmd
    # - 07-content.qmd
    # - 08-content.qmd
    - references.qmd
  

bibliography: references.bib

format:
  html:
    theme: [cosmo, style.scss]
    number-depth: 1
    toc-depth: 2
    echo: fenced
    warning: false
    message: false
    embed-resources: true
    embed-resources-math: true
  pdf:
    documentclass: scrreprt
    keep-tex: true
    include-in-header: columns.tex
    number-depth: 1
    toc-depth: 2
    echo: fenced
    warning: false
    message: false
    embed-resources: true
    embed-resources-math: true


from: markdown+emoji

